import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tools: [{
    type: 'category',
    label: 'ID生成工具',
    link: {
      type: 'generated-index',
      title: 'ID生成工具',
      description: '提供多种主流ID生成方案，支持批量生成和自定义配置',
      keywords: ['id', 'uuid', 'nanoid', 'snowflake'],
      slug: '/id_gen',
    },
    items: [
      'tools/id_generator/uuid',
      'tools/id_generator/nanoid',
      'tools/id_generator/snowflakeid',
    ],
  },
    {
      type: 'category',
      label: '密码安全工具',
      link: {
        type: 'generated-index',
        title: '密码安全工具',
        description: '提供密码生成和强度评估功能，帮助提升账户安全性',
        keywords: ['密码', 'password', '强度'],
        slug: '/password',
      },
      items: [
        'tools/password_generator/password_generator',
        'tools/password_complexity_calculator/password_complexity_calculator',
      ],
    },
    {
      type: 'category',
      label: '加密工具',
      link: {
        type: 'generated-index',
        title: '加密工具',
        description: '提供多种常用的加密和哈希算法，支持HMAC模式，可自定义变量和参数',
        keywords: ['md5', 'sha', '加密', '哈希'],
        slug: '/sec',
      },
      items: [
        'tools/endecryption/md5',
        'tools/endecryption/sha',
        'tools/endecryption/digest',
      ],
    },
    {
      type: 'category',
      label: '家装建筑工具',
      link: {
        type: 'generated-index',
        title: '家装建筑工具',
        description: '提供常用的家装建筑场景需要用到的在线工具',
        keywords: ['坡度', '比例', '配方', '建筑'],
        slug: '/building',
      },
      items: [
        'tools/building/slope',
        'tools/building/proportion',
        'tools/building/recipe_proportion',
      ],
    },
    {
      type: 'category',
      label: '生活与烹饪助手',
      link: {
        type: 'generated-index',
        title: '生活与烹饪助手',
        description: '提供日常生活中常用的换算与辅助工具',
        keywords: ['配料', '烹饪', '比例'],
        slug: '/lifestyle',
      },
      items: [
        'tools/building/cooking',
      ],
    },
  ],
};

export default sidebars;
